services:
  app:
    build:
      context: ..
      dockerfile: Docker/Dockerfile
      args:
        - APP_VERSION=${APP_VERSION}
    #    image: ${DOCKER_USERNAME}/${APP_NAME}:${APP_VERSION}
    container_name: ${APP_NAME}-api
    restart: always
    ports:
      - "8080:${HTTP_PORT}"
    environment:
      - APP_NAME=${APP_NAME}
      - APP_VERSION=${APP_VERSION}
      - HTTP_PORT=${HTTP_PORT}
      - LOG_LEVEL=${LOG_LEVEL}
      - PG_POOL_MAX=${PG_POOL_MAX}
      - PG_URL=${PG_URL}
      - SWAGGER_ENABLED=${SWAGGER_ENABLED}
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: spycat-db
    environment:
      - POSTGRES_USER=${PG_USERNAME}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DB}
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata: